### ISSUE TITLE
Add a "Fork me on Github" Ribbon

### ISSUE THREAD

**Issue by vishvanath45** [vishvanath45/CodeHike#5]
You can refer for more information over [here.](https://blog.github.com/2008-12-19-github-ribbons/)

**Comment by vishvanath45** [comment]
@Jayadev6191,  @LOC1207  This might interest you guys. :-)

**Comment by wabdul539** [comment]
i am working on this. May you please assign this issue to me?

**Comment by vishvanath45** [comment]
@wabdul539 you can work on this, there is some problem in assigning people apart from contributor.

**Comment by vishvanath45** [comment]
@wabdul539 Please look into my review.

**Comment by wabdul539** [comment]
@vishvanath45 I am not able to see any review.

**Comment by vishvanath45** [comment]
Closing as it is fixed in #14.
